/**
 * Vercel Function: Enhance content using Gemini AI
 * Endpoint: POST /api/enhance-content
 */

import type { VercelRequest, VercelResponse } from '@vercel/node';

interface EnhanceRequest {
  content: string; // Markdown content to enhance
  instructions?: string; // Optional user instructions
  documentName?: string; // Optional document name for context
}

interface EnhanceResponse {
  enhancedContent: string; // Enhanced markdown
  model: string; // Model used
}

export default async function handler(req: VercelRequest, res: VercelResponse) {
  // Only allow POST requests
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { content, instructions, documentName } = req.body as EnhanceRequest;

  // Validate input
  if (!content || typeof content !== 'string') {
    return res.status(400).json({
      error: 'Missing or invalid content parameter',
    });
  }

  if (content.trim().length === 0) {
    return res.status(400).json({
      error: 'Content cannot be empty',
    });
  }

  // Get API key from environment
  const apiKey = process.env.GEMINI_API_KEY;

  if (!apiKey) {
    return res.status(500).json({
      error: 'Server configuration error: GEMINI_API_KEY not set',
    });
  }

  try {
    // Build prompt for Gemini
    const systemPrompt = `You are a technical documentation enhancement assistant. Your task is to improve technical documentation by:

1. Adding implementation details and code examples where appropriate
2. Clarifying technical concepts and terminology
3. Improving structure and readability
4. Adding best practices and recommendations
5. Maintaining professional technical writing style

Important guidelines:
- Keep the same overall structure and organization
- Output ONLY in Markdown format
- Be concise but thorough
- Focus on practical, actionable information
- Add code examples in appropriate language with syntax highlighting
- Use tables for comparing options when relevant
- Add notes/warnings for important considerations

${documentName ? `Document name: "${documentName}"` : ''}
${instructions ? `\nUser instructions:\n${instructions}` : ''}`;

    const userPrompt = `Please enhance the following technical documentation:

${content}`;

    // Call Gemini API
    const geminiUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:generateContent?key=${apiKey}`;

    const geminiResponse = await fetch(geminiUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [
          {
            parts: [
              {
                text: `${systemPrompt}\n\n${userPrompt}`,
              },
            ],
          },
        ],
        generationConfig: {
          temperature: 0.7,
          maxOutputTokens: 8192,
          topP: 0.95,
          topK: 40,
        },
        safetySettings: [
          {
            category: 'HARM_CATEGORY_HARASSMENT',
            threshold: 'BLOCK_NONE',
          },
          {
            category: 'HARM_CATEGORY_HATE_SPEECH',
            threshold: 'BLOCK_NONE',
          },
          {
            category: 'HARM_CATEGORY_SEXUALLY_EXPLICIT',
            threshold: 'BLOCK_NONE',
          },
          {
            category: 'HARM_CATEGORY_DANGEROUS_CONTENT',
            threshold: 'BLOCK_NONE',
          },
        ],
      }),
    });

    if (!geminiResponse.ok) {
      const errorText = await geminiResponse.text();
      console.error('Gemini API error:', geminiResponse.status, errorText);

      if (geminiResponse.status === 429) {
        return res.status(429).json({
          error: 'Rate limit exceeded. Please try again later.',
        });
      }

      return res.status(geminiResponse.status).json({
        error: `Gemini API error: ${geminiResponse.statusText}`,
      });
    }

    const data = await geminiResponse.json();

    // Extract enhanced content
    const enhancedContent = data.candidates?.[0]?.content?.parts?.[0]?.text || content;

    if (!enhancedContent) {
      return res.status(500).json({
        error: 'No content generated by AI',
      });
    }

    const result: EnhanceResponse = {
      enhancedContent,
      model: 'gemini-2.0-flash-exp',
    };

    return res.status(200).json(result);
  } catch (error) {
    console.error('Failed to enhance content:', error);
    return res.status(500).json({
      error: 'Failed to enhance content',
      details: error instanceof Error ? error.message : 'Unknown error',
    });
  }
}
